# Generated by Django 4.2.4 on 2023-09-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cpassword', models.CharField(max_length=255)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
